# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from chinju_vllm.proto.chinju import capability_pb2 as chinju_dot_capability__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in chinju/api/capability_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CapabilityEvaluatorStub(object):
    """Multi-Dimensional Capability Evaluator Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EvaluateComplexity = channel.unary_unary(
                '/chinju.api.capability.CapabilityEvaluator/EvaluateComplexity',
                request_serializer=chinju_dot_capability__pb2.EvaluateComplexityRequest.SerializeToString,
                response_deserializer=chinju_dot_capability__pb2.ComplexityEvaluation.FromString,
                _registered_method=True)
        self.VerifyIntegrity = channel.unary_unary(
                '/chinju.api.capability.CapabilityEvaluator/VerifyIntegrity',
                request_serializer=chinju_dot_capability__pb2.VerifyIntegrityRequest.SerializeToString,
                response_deserializer=chinju_dot_capability__pb2.IntegrityVerification.FromString,
                _registered_method=True)
        self.DetectDrift = channel.unary_unary(
                '/chinju.api.capability.CapabilityEvaluator/DetectDrift',
                request_serializer=chinju_dot_capability__pb2.DetectDriftRequest.SerializeToString,
                response_deserializer=chinju_dot_capability__pb2.DriftDetection.FromString,
                _registered_method=True)
        self.GetEvaluationSummary = channel.unary_unary(
                '/chinju.api.capability.CapabilityEvaluator/GetEvaluationSummary',
                request_serializer=chinju_dot_capability__pb2.GetEvaluationSummaryRequest.SerializeToString,
                response_deserializer=chinju_dot_capability__pb2.CapabilityEvaluationSummary.FromString,
                _registered_method=True)
        self.DirectStop = channel.unary_unary(
                '/chinju.api.capability.CapabilityEvaluator/DirectStop',
                request_serializer=chinju_dot_capability__pb2.DirectStopRequest.SerializeToString,
                response_deserializer=chinju_dot_capability__pb2.DirectStopResponse.FromString,
                _registered_method=True)


class CapabilityEvaluatorServicer(object):
    """Multi-Dimensional Capability Evaluator Service
    """

    def EvaluateComplexity(self, request, context):
        """Evaluate complexity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyIntegrity(self, request, context):
        """Verify integrity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectDrift(self, request, context):
        """Detect drift
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEvaluationSummary(self, request, context):
        """Get evaluation summary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DirectStop(self, request, context):
        """Direct stop
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CapabilityEvaluatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EvaluateComplexity': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateComplexity,
                    request_deserializer=chinju_dot_capability__pb2.EvaluateComplexityRequest.FromString,
                    response_serializer=chinju_dot_capability__pb2.ComplexityEvaluation.SerializeToString,
            ),
            'VerifyIntegrity': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyIntegrity,
                    request_deserializer=chinju_dot_capability__pb2.VerifyIntegrityRequest.FromString,
                    response_serializer=chinju_dot_capability__pb2.IntegrityVerification.SerializeToString,
            ),
            'DetectDrift': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectDrift,
                    request_deserializer=chinju_dot_capability__pb2.DetectDriftRequest.FromString,
                    response_serializer=chinju_dot_capability__pb2.DriftDetection.SerializeToString,
            ),
            'GetEvaluationSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEvaluationSummary,
                    request_deserializer=chinju_dot_capability__pb2.GetEvaluationSummaryRequest.FromString,
                    response_serializer=chinju_dot_capability__pb2.CapabilityEvaluationSummary.SerializeToString,
            ),
            'DirectStop': grpc.unary_unary_rpc_method_handler(
                    servicer.DirectStop,
                    request_deserializer=chinju_dot_capability__pb2.DirectStopRequest.FromString,
                    response_serializer=chinju_dot_capability__pb2.DirectStopResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chinju.api.capability.CapabilityEvaluator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chinju.api.capability.CapabilityEvaluator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CapabilityEvaluator(object):
    """Multi-Dimensional Capability Evaluator Service
    """

    @staticmethod
    def EvaluateComplexity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chinju.api.capability.CapabilityEvaluator/EvaluateComplexity',
            chinju_dot_capability__pb2.EvaluateComplexityRequest.SerializeToString,
            chinju_dot_capability__pb2.ComplexityEvaluation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyIntegrity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chinju.api.capability.CapabilityEvaluator/VerifyIntegrity',
            chinju_dot_capability__pb2.VerifyIntegrityRequest.SerializeToString,
            chinju_dot_capability__pb2.IntegrityVerification.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectDrift(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chinju.api.capability.CapabilityEvaluator/DetectDrift',
            chinju_dot_capability__pb2.DetectDriftRequest.SerializeToString,
            chinju_dot_capability__pb2.DriftDetection.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEvaluationSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chinju.api.capability.CapabilityEvaluator/GetEvaluationSummary',
            chinju_dot_capability__pb2.GetEvaluationSummaryRequest.SerializeToString,
            chinju_dot_capability__pb2.CapabilityEvaluationSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DirectStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chinju.api.capability.CapabilityEvaluator/DirectStop',
            chinju_dot_capability__pb2.DirectStopRequest.SerializeToString,
            chinju_dot_capability__pb2.DirectStopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
