# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chinju/api/capability_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chinju/api/capability_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chinju_vllm.proto.chinju import capability_pb2 as chinju_dot_capability__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#chinju/api/capability_service.proto\x12\x15\x63hinju.api.capability\x1a\x17\x63hinju/capability.proto2\x96\x04\n\x13\x43\x61pabilityEvaluator\x12k\n\x12\x45valuateComplexity\x12,.chinju.capability.EvaluateComplexityRequest\x1a\'.chinju.capability.ComplexityEvaluation\x12\x66\n\x0fVerifyIntegrity\x12).chinju.capability.VerifyIntegrityRequest\x1a(.chinju.capability.IntegrityVerification\x12W\n\x0b\x44\x65tectDrift\x12%.chinju.capability.DetectDriftRequest\x1a!.chinju.capability.DriftDetection\x12v\n\x14GetEvaluationSummary\x12..chinju.capability.GetEvaluationSummaryRequest\x1a..chinju.capability.CapabilityEvaluationSummary\x12Y\n\nDirectStop\x12$.chinju.capability.DirectStopRequest\x1a%.chinju.capability.DirectStopResponseBf\n\"org.chinju.protocol.api.capabilityP\x01Z>github.com/chinju-protocol/chinju-go/gen/chinju/api/capabilityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chinju.api.capability_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\"org.chinju.protocol.api.capabilityP\001Z>github.com/chinju-protocol/chinju-go/gen/chinju/api/capability'
  _globals['_CAPABILITYEVALUATOR']._serialized_start=88
  _globals['_CAPABILITYEVALUATOR']._serialized_end=622
# @@protoc_insertion_point(module_scope)
