# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chinju/api/contradiction_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chinju/api/contradiction_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chinju_vllm.proto.chinju import contradiction_pb2 as chinju_dot_contradiction__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&chinju/api/contradiction_service.proto\x12\x18\x63hinju.api.contradiction\x1a\x1a\x63hinju/contradiction.proto2\xda\x03\n\x17\x43ontradictionController\x12u\n\x0cStartControl\x12\x31.chinju.contradiction.ContradictionControlRequest\x1a\x32.chinju.contradiction.ContradictionControlResponse\x12n\n\x0fGetControlState\x12,.chinju.contradiction.GetControlStateRequest\x1a-.chinju.contradiction.GetControlStateResponse\x12\x62\n\x0bStopControl\x12(.chinju.contradiction.StopControlRequest\x1a).chinju.contradiction.StopControlResponse\x12t\n\x11TestContradiction\x12..chinju.contradiction.TestContradictionRequest\x1a/.chinju.contradiction.TestContradictionResponseBl\n%org.chinju.protocol.api.contradictionP\x01ZAgithub.com/chinju-protocol/chinju-go/gen/chinju/api/contradictionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chinju.api.contradiction_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chinju.protocol.api.contradictionP\001ZAgithub.com/chinju-protocol/chinju-go/gen/chinju/api/contradiction'
  _globals['_CONTRADICTIONCONTROLLER']._serialized_start=97
  _globals['_CONTRADICTIONCONTROLLER']._serialized_end=571
# @@protoc_insertion_point(module_scope)
