# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from chinju_vllm.proto.chinju import contradiction_pb2 as chinju_dot_contradiction__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in chinju/api/contradiction_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ContradictionControllerStub(object):
    """Contradiction Controller Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartControl = channel.unary_unary(
                '/chinju.api.contradiction.ContradictionController/StartControl',
                request_serializer=chinju_dot_contradiction__pb2.ContradictionControlRequest.SerializeToString,
                response_deserializer=chinju_dot_contradiction__pb2.ContradictionControlResponse.FromString,
                _registered_method=True)
        self.GetControlState = channel.unary_unary(
                '/chinju.api.contradiction.ContradictionController/GetControlState',
                request_serializer=chinju_dot_contradiction__pb2.GetControlStateRequest.SerializeToString,
                response_deserializer=chinju_dot_contradiction__pb2.GetControlStateResponse.FromString,
                _registered_method=True)
        self.StopControl = channel.unary_unary(
                '/chinju.api.contradiction.ContradictionController/StopControl',
                request_serializer=chinju_dot_contradiction__pb2.StopControlRequest.SerializeToString,
                response_deserializer=chinju_dot_contradiction__pb2.StopControlResponse.FromString,
                _registered_method=True)
        self.TestContradiction = channel.unary_unary(
                '/chinju.api.contradiction.ContradictionController/TestContradiction',
                request_serializer=chinju_dot_contradiction__pb2.TestContradictionRequest.SerializeToString,
                response_deserializer=chinju_dot_contradiction__pb2.TestContradictionResponse.FromString,
                _registered_method=True)


class ContradictionControllerServicer(object):
    """Contradiction Controller Service
    """

    def StartControl(self, request, context):
        """Start contradiction injection control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetControlState(self, request, context):
        """Get control state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopControl(self, request, context):
        """Stop control (recovery)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestContradiction(self, request, context):
        """Test contradiction pattern (dry run)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContradictionControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartControl': grpc.unary_unary_rpc_method_handler(
                    servicer.StartControl,
                    request_deserializer=chinju_dot_contradiction__pb2.ContradictionControlRequest.FromString,
                    response_serializer=chinju_dot_contradiction__pb2.ContradictionControlResponse.SerializeToString,
            ),
            'GetControlState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetControlState,
                    request_deserializer=chinju_dot_contradiction__pb2.GetControlStateRequest.FromString,
                    response_serializer=chinju_dot_contradiction__pb2.GetControlStateResponse.SerializeToString,
            ),
            'StopControl': grpc.unary_unary_rpc_method_handler(
                    servicer.StopControl,
                    request_deserializer=chinju_dot_contradiction__pb2.StopControlRequest.FromString,
                    response_serializer=chinju_dot_contradiction__pb2.StopControlResponse.SerializeToString,
            ),
            'TestContradiction': grpc.unary_unary_rpc_method_handler(
                    servicer.TestContradiction,
                    request_deserializer=chinju_dot_contradiction__pb2.TestContradictionRequest.FromString,
                    response_serializer=chinju_dot_contradiction__pb2.TestContradictionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chinju.api.contradiction.ContradictionController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chinju.api.contradiction.ContradictionController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ContradictionController(object):
    """Contradiction Controller Service
    """

    @staticmethod
    def StartControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chinju.api.contradiction.ContradictionController/StartControl',
            chinju_dot_contradiction__pb2.ContradictionControlRequest.SerializeToString,
            chinju_dot_contradiction__pb2.ContradictionControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetControlState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chinju.api.contradiction.ContradictionController/GetControlState',
            chinju_dot_contradiction__pb2.GetControlStateRequest.SerializeToString,
            chinju_dot_contradiction__pb2.GetControlStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chinju.api.contradiction.ContradictionController/StopControl',
            chinju_dot_contradiction__pb2.StopControlRequest.SerializeToString,
            chinju_dot_contradiction__pb2.StopControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TestContradiction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chinju.api.contradiction.ContradictionController/TestContradiction',
            chinju_dot_contradiction__pb2.TestContradictionRequest.SerializeToString,
            chinju_dot_contradiction__pb2.TestContradictionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
