# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from chinju_vllm.proto.chinju import survival_attention_pb2 as chinju_dot_survival__attention__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in chinju/api/survival_attention_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SurvivalAttentionServiceStub(object):
    """Survival-Weighted Attention Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComputeSurvivalScores = channel.unary_unary(
                '/chinju.api.survival_attention.SurvivalAttentionService/ComputeSurvivalScores',
                request_serializer=chinju_dot_survival__attention__pb2.ComputeScoresRequest.SerializeToString,
                response_deserializer=chinju_dot_survival__attention__pb2.TokenSurvivalScores.FromString,
                _registered_method=True)
        self.InferWithSurvivalAttention = channel.unary_unary(
                '/chinju.api.survival_attention.SurvivalAttentionService/InferWithSurvivalAttention',
                request_serializer=chinju_dot_survival__attention__pb2.SurvivalAttentionRequest.SerializeToString,
                response_deserializer=chinju_dot_survival__attention__pb2.SurvivalAttentionResponse.FromString,
                _registered_method=True)
        self.AdjustAlpha = channel.unary_unary(
                '/chinju.api.survival_attention.SurvivalAttentionService/AdjustAlpha',
                request_serializer=chinju_dot_survival__attention__pb2.AdjustAlphaRequest.SerializeToString,
                response_deserializer=chinju_dot_survival__attention__pb2.AdjustAlphaResponse.FromString,
                _registered_method=True)
        self.UpdateScorer = channel.unary_unary(
                '/chinju.api.survival_attention.SurvivalAttentionService/UpdateScorer',
                request_serializer=chinju_dot_survival__attention__pb2.UpdateScorerRequest.SerializeToString,
                response_deserializer=chinju_dot_survival__attention__pb2.UpdateScorerResponse.FromString,
                _registered_method=True)


class SurvivalAttentionServiceServicer(object):
    """Survival-Weighted Attention Service
    """

    def ComputeSurvivalScores(self, request, context):
        """Compute survival scores
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InferWithSurvivalAttention(self, request, context):
        """Infer with SurvivalAttention
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdjustAlpha(self, request, context):
        """Adjust alpha dynamically
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateScorer(self, request, context):
        """Update SurvivalScorer model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SurvivalAttentionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComputeSurvivalScores': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeSurvivalScores,
                    request_deserializer=chinju_dot_survival__attention__pb2.ComputeScoresRequest.FromString,
                    response_serializer=chinju_dot_survival__attention__pb2.TokenSurvivalScores.SerializeToString,
            ),
            'InferWithSurvivalAttention': grpc.unary_unary_rpc_method_handler(
                    servicer.InferWithSurvivalAttention,
                    request_deserializer=chinju_dot_survival__attention__pb2.SurvivalAttentionRequest.FromString,
                    response_serializer=chinju_dot_survival__attention__pb2.SurvivalAttentionResponse.SerializeToString,
            ),
            'AdjustAlpha': grpc.unary_unary_rpc_method_handler(
                    servicer.AdjustAlpha,
                    request_deserializer=chinju_dot_survival__attention__pb2.AdjustAlphaRequest.FromString,
                    response_serializer=chinju_dot_survival__attention__pb2.AdjustAlphaResponse.SerializeToString,
            ),
            'UpdateScorer': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateScorer,
                    request_deserializer=chinju_dot_survival__attention__pb2.UpdateScorerRequest.FromString,
                    response_serializer=chinju_dot_survival__attention__pb2.UpdateScorerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chinju.api.survival_attention.SurvivalAttentionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chinju.api.survival_attention.SurvivalAttentionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SurvivalAttentionService(object):
    """Survival-Weighted Attention Service
    """

    @staticmethod
    def ComputeSurvivalScores(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chinju.api.survival_attention.SurvivalAttentionService/ComputeSurvivalScores',
            chinju_dot_survival__attention__pb2.ComputeScoresRequest.SerializeToString,
            chinju_dot_survival__attention__pb2.TokenSurvivalScores.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InferWithSurvivalAttention(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chinju.api.survival_attention.SurvivalAttentionService/InferWithSurvivalAttention',
            chinju_dot_survival__attention__pb2.SurvivalAttentionRequest.SerializeToString,
            chinju_dot_survival__attention__pb2.SurvivalAttentionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdjustAlpha(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chinju.api.survival_attention.SurvivalAttentionService/AdjustAlpha',
            chinju_dot_survival__attention__pb2.AdjustAlphaRequest.SerializeToString,
            chinju_dot_survival__attention__pb2.AdjustAlphaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateScorer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chinju.api.survival_attention.SurvivalAttentionService/UpdateScorer',
            chinju_dot_survival__attention__pb2.UpdateScorerRequest.SerializeToString,
            chinju_dot_survival__attention__pb2.UpdateScorerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
