# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chinju/api/survival_attention_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chinju/api/survival_attention_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chinju_vllm.proto.chinju import survival_attention_pb2 as chinju_dot_survival__attention__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+chinju/api/survival_attention_service.proto\x12\x1d\x63hinju.api.survival_attention\x1a\x1f\x63hinju/survival_attention.proto2\xfd\x03\n\x18SurvivalAttentionService\x12x\n\x15\x43omputeSurvivalScores\x12/.chinju.survival_attention.ComputeScoresRequest\x1a..chinju.survival_attention.TokenSurvivalScores\x12\x87\x01\n\x1aInferWithSurvivalAttention\x12\x33.chinju.survival_attention.SurvivalAttentionRequest\x1a\x34.chinju.survival_attention.SurvivalAttentionResponse\x12l\n\x0b\x41\x64justAlpha\x12-.chinju.survival_attention.AdjustAlphaRequest\x1a..chinju.survival_attention.AdjustAlphaResponse\x12o\n\x0cUpdateScorer\x12..chinju.survival_attention.UpdateScorerRequest\x1a/.chinju.survival_attention.UpdateScorerResponseBv\n*org.chinju.protocol.api.survival_attentionP\x01ZFgithub.com/chinju-protocol/chinju-go/gen/chinju/api/survival_attentionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chinju.api.survival_attention_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n*org.chinju.protocol.api.survival_attentionP\001ZFgithub.com/chinju-protocol/chinju-go/gen/chinju/api/survival_attention'
  _globals['_SURVIVALATTENTIONSERVICE']._serialized_start=112
  _globals['_SURVIVALATTENTIONSERVICE']._serialized_end=621
# @@protoc_insertion_point(module_scope)
