# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from chinju_vllm.proto.chinju import value_neuron_pb2 as chinju_dot_value__neuron__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in chinju/api/value_neuron_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ValueNeuronMonitorStub(object):
    """Value Neuron Monitor Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IdentifyValueNeurons = channel.unary_stream(
                '/chinju.api.value_neuron.ValueNeuronMonitor/IdentifyValueNeurons',
                request_serializer=chinju_dot_value__neuron__pb2.IdentifyRequest.SerializeToString,
                response_deserializer=chinju_dot_value__neuron__pb2.ValueNeuronInfo.FromString,
                _registered_method=True)
        self.GetRpeReading = channel.unary_unary(
                '/chinju.api.value_neuron.ValueNeuronMonitor/GetRpeReading',
                request_serializer=chinju_dot_value__neuron__pb2.RpeRequest.SerializeToString,
                response_deserializer=chinju_dot_value__neuron__pb2.RpeReading.FromString,
                _registered_method=True)
        self.GetRpeHistory = channel.unary_stream(
                '/chinju.api.value_neuron.ValueNeuronMonitor/GetRpeHistory',
                request_serializer=chinju_dot_value__neuron__pb2.RpeHistoryRequest.SerializeToString,
                response_deserializer=chinju_dot_value__neuron__pb2.RpeReading.FromString,
                _registered_method=True)
        self.EstimateIntent = channel.unary_unary(
                '/chinju.api.value_neuron.ValueNeuronMonitor/EstimateIntent',
                request_serializer=chinju_dot_value__neuron__pb2.IntentRequest.SerializeToString,
                response_deserializer=chinju_dot_value__neuron__pb2.IntentEstimation.FromString,
                _registered_method=True)
        self.DiagnoseHealth = channel.unary_unary(
                '/chinju.api.value_neuron.ValueNeuronMonitor/DiagnoseHealth',
                request_serializer=chinju_dot_value__neuron__pb2.DiagnoseRequest.SerializeToString,
                response_deserializer=chinju_dot_value__neuron__pb2.RewardSystemHealth.FromString,
                _registered_method=True)
        self.GetMonitoringSummary = channel.unary_unary(
                '/chinju.api.value_neuron.ValueNeuronMonitor/GetMonitoringSummary',
                request_serializer=chinju_dot_value__neuron__pb2.SummaryRequest.SerializeToString,
                response_deserializer=chinju_dot_value__neuron__pb2.ValueNeuronMonitoringSummary.FromString,
                _registered_method=True)
        self.Intervene = channel.unary_unary(
                '/chinju.api.value_neuron.ValueNeuronMonitor/Intervene',
                request_serializer=chinju_dot_value__neuron__pb2.InterventionRequest.SerializeToString,
                response_deserializer=chinju_dot_value__neuron__pb2.InterventionResponse.FromString,
                _registered_method=True)


class ValueNeuronMonitorServicer(object):
    """Value Neuron Monitor Service
    """

    def IdentifyValueNeurons(self, request, context):
        """Identify value neurons
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRpeReading(self, request, context):
        """Get RPE reading
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRpeHistory(self, request, context):
        """Get RPE history
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstimateIntent(self, request, context):
        """Estimate intent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiagnoseHealth(self, request, context):
        """Diagnose reward system health
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMonitoringSummary(self, request, context):
        """Get monitoring summary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Intervene(self, request, context):
        """Intervene
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ValueNeuronMonitorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IdentifyValueNeurons': grpc.unary_stream_rpc_method_handler(
                    servicer.IdentifyValueNeurons,
                    request_deserializer=chinju_dot_value__neuron__pb2.IdentifyRequest.FromString,
                    response_serializer=chinju_dot_value__neuron__pb2.ValueNeuronInfo.SerializeToString,
            ),
            'GetRpeReading': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRpeReading,
                    request_deserializer=chinju_dot_value__neuron__pb2.RpeRequest.FromString,
                    response_serializer=chinju_dot_value__neuron__pb2.RpeReading.SerializeToString,
            ),
            'GetRpeHistory': grpc.unary_stream_rpc_method_handler(
                    servicer.GetRpeHistory,
                    request_deserializer=chinju_dot_value__neuron__pb2.RpeHistoryRequest.FromString,
                    response_serializer=chinju_dot_value__neuron__pb2.RpeReading.SerializeToString,
            ),
            'EstimateIntent': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimateIntent,
                    request_deserializer=chinju_dot_value__neuron__pb2.IntentRequest.FromString,
                    response_serializer=chinju_dot_value__neuron__pb2.IntentEstimation.SerializeToString,
            ),
            'DiagnoseHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.DiagnoseHealth,
                    request_deserializer=chinju_dot_value__neuron__pb2.DiagnoseRequest.FromString,
                    response_serializer=chinju_dot_value__neuron__pb2.RewardSystemHealth.SerializeToString,
            ),
            'GetMonitoringSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMonitoringSummary,
                    request_deserializer=chinju_dot_value__neuron__pb2.SummaryRequest.FromString,
                    response_serializer=chinju_dot_value__neuron__pb2.ValueNeuronMonitoringSummary.SerializeToString,
            ),
            'Intervene': grpc.unary_unary_rpc_method_handler(
                    servicer.Intervene,
                    request_deserializer=chinju_dot_value__neuron__pb2.InterventionRequest.FromString,
                    response_serializer=chinju_dot_value__neuron__pb2.InterventionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chinju.api.value_neuron.ValueNeuronMonitor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chinju.api.value_neuron.ValueNeuronMonitor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ValueNeuronMonitor(object):
    """Value Neuron Monitor Service
    """

    @staticmethod
    def IdentifyValueNeurons(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/chinju.api.value_neuron.ValueNeuronMonitor/IdentifyValueNeurons',
            chinju_dot_value__neuron__pb2.IdentifyRequest.SerializeToString,
            chinju_dot_value__neuron__pb2.ValueNeuronInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRpeReading(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chinju.api.value_neuron.ValueNeuronMonitor/GetRpeReading',
            chinju_dot_value__neuron__pb2.RpeRequest.SerializeToString,
            chinju_dot_value__neuron__pb2.RpeReading.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRpeHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/chinju.api.value_neuron.ValueNeuronMonitor/GetRpeHistory',
            chinju_dot_value__neuron__pb2.RpeHistoryRequest.SerializeToString,
            chinju_dot_value__neuron__pb2.RpeReading.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EstimateIntent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chinju.api.value_neuron.ValueNeuronMonitor/EstimateIntent',
            chinju_dot_value__neuron__pb2.IntentRequest.SerializeToString,
            chinju_dot_value__neuron__pb2.IntentEstimation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DiagnoseHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chinju.api.value_neuron.ValueNeuronMonitor/DiagnoseHealth',
            chinju_dot_value__neuron__pb2.DiagnoseRequest.SerializeToString,
            chinju_dot_value__neuron__pb2.RewardSystemHealth.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMonitoringSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chinju.api.value_neuron.ValueNeuronMonitor/GetMonitoringSummary',
            chinju_dot_value__neuron__pb2.SummaryRequest.SerializeToString,
            chinju_dot_value__neuron__pb2.ValueNeuronMonitoringSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Intervene(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chinju.api.value_neuron.ValueNeuronMonitor/Intervene',
            chinju_dot_value__neuron__pb2.InterventionRequest.SerializeToString,
            chinju_dot_value__neuron__pb2.InterventionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
