# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chinju/api/value_neuron_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chinju/api/value_neuron_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chinju_vllm.proto.chinju import value_neuron_pb2 as chinju_dot_value__neuron__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%chinju/api/value_neuron_service.proto\x12\x17\x63hinju.api.value_neuron\x1a\x19\x63hinju/value_neuron.proto2\xb9\x05\n\x12ValueNeuronMonitor\x12\x64\n\x14IdentifyValueNeurons\x12$.chinju.value_neuron.IdentifyRequest\x1a$.chinju.value_neuron.ValueNeuronInfo0\x01\x12Q\n\rGetRpeReading\x12\x1f.chinju.value_neuron.RpeRequest\x1a\x1f.chinju.value_neuron.RpeReading\x12Z\n\rGetRpeHistory\x12&.chinju.value_neuron.RpeHistoryRequest\x1a\x1f.chinju.value_neuron.RpeReading0\x01\x12[\n\x0e\x45stimateIntent\x12\".chinju.value_neuron.IntentRequest\x1a%.chinju.value_neuron.IntentEstimation\x12_\n\x0e\x44iagnoseHealth\x12$.chinju.value_neuron.DiagnoseRequest\x1a\'.chinju.value_neuron.RewardSystemHealth\x12n\n\x14GetMonitoringSummary\x12#.chinju.value_neuron.SummaryRequest\x1a\x31.chinju.value_neuron.ValueNeuronMonitoringSummary\x12`\n\tIntervene\x12(.chinju.value_neuron.InterventionRequest\x1a).chinju.value_neuron.InterventionResponseBj\n$org.chinju.protocol.api.value_neuronP\x01Z@github.com/chinju-protocol/chinju-go/gen/chinju/api/value_neuronb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chinju.api.value_neuron_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$org.chinju.protocol.api.value_neuronP\001Z@github.com/chinju-protocol/chinju-go/gen/chinju/api/value_neuron'
  _globals['_VALUENEURONMONITOR']._serialized_start=94
  _globals['_VALUENEURONMONITOR']._serialized_end=791
# @@protoc_insertion_point(module_scope)
